### ISSUE TITLE
Camera switch binding not working with 101a

### ISSUE THREAD

**Issue by Joshayyx** [TheGag96/sm64ex#2]
I've installed the patch through sm64 pc builder 2 and the moveset works but I can't change the camera with the D-pad. I'm also using the better camera patch.

**Comment by mariotime1287** [comment]
I also noticed this. You can disable "Free Camera" and that makes the dpad bind work, but annoyingly, it can't work with Free Camera enabled.

**Comment by Joshayyx** [comment]
I can't seem to get it to work even with free camera disabled.

**Comment by mariotime1287** [comment]
I've figured out a fix. go to %appdata% (the same place where you find Minecraft's files, if that helps) and look for "sm64ex". And then delete or rename "sm64config.txt". Then it should work. (You will have to remap all your controls, video settings, etc.)

**Comment by Joshayyx** [comment]
I just tried this and it still didn't work.

**Comment by mariotime1287** [comment]
Yeah, it seems the issue has become a bit worse. On the latest version it seems the bug causing better camera to bind to R rather than d-pad is a lot worse than before.
The fix I listed seemed to have worked on the older version of either bettercamera or extended moveset, but one or the other has updated since and caused this bug to reappear.

**Comment by Joshayyx** [comment]
Now that the extended moveset is on the sm64 builder the issue is fixed. You have to rebuild the game with the built in version on this mod.
